version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - my-database
    
  my-database:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - my-redis-data:/data
volumes:
  my-redis-data: